### ISSUE TITLE
Add a favorites view and favorites management

### ISSUE THREAD

**Issue by che-** [52North/js-sensorweb-client#76]
Add a listview of favorites that shows the latest value of each favorite and offers the following buttons for each entzry: show in chart, show in map, remove from favoritelist.

Allow users to add timeseries to this favorites list in legend as well as in the station window. (star icon)

For now use HTML5 localStaorage, maybe switch to a serverside solution later.

**Comment by janschulte** [comment]
Added with Release 1.0.0
